### ISSUE TITLE
Ask a question about SSIM^(-1) in the paper

### ISSUE THREAD

**Issue by howfars** [kaist-ina/NAS_public#12]
In the part 5.3 of the paper,the function SSIM^(-1) was defined.
The paper said "To create the mapping, we measure the SSIM of original video chunks at each bitrate (or resolution) and use piece-wise linear interpolation (e.g., (400 Kbps, SSIM1), ..., (4800 Kbps, SSIM5))".
![image](https://user-images.githubusercontent.com/24860642/99473579-cce6d080-2985-11eb-978f-2a8dffd05a25.png)
And I have a question about this :
When caculating the R_effective(C_n),we use the SSIM(-1) function to map a ssim value to a corresponding effective bitrate.
However, the bitrate values are discrete,  what if there are no corresponding bitrate for a ssim value in the mesurement data (400 Kbps, SSIM1), ..., (4800 Kbps, SSIM5)).
For example, we have mesurement data like this:
(400Kbps,SSIM1),(800Kbps,SSIM2)...(4800Kbps,SSIM5)
Now we have a SR reconstructed chunk, whose SSIM value is greater than SSIM1 and less than SSIM2,then how do we get the effective bitrate of this chunk?
Do you mean we can do a linear interpolation in those discrete mesurement data?

**Comment by chaos5958** [comment]
Hi, thanks for interest in our paper!

In our experiment, we did a linear interpolation to get an effective bitrate.
But, if you have more data, you can build a more precise function.

**Comment by howfars** [comment]
Thank you for your answer,it's very helpful!
