### ISSUE TITLE
testing error

### ISSUE THREAD

**Issue by RavaliKolli** [kaist-ina/NAS_public#4]
File "/home/ubuntu/NAS_public/process.py", line 366, in encode
    pipe.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
decode [super-resolution]: 1.8120205402374268sec

not sure why this error happened. can you guys help me out?

**Comment by chaos5958** [comment]
Hi, Ravali.

I've experience this error when opencv is not setup properly (mostly due to inadequate versions).
Have you tried opencv by Anaconda specified in README?
Since this is an error due to opencv, stackoverflow might be also helpful.

**Comment by RavaliKolli** [comment]
Thank you so much for the reply, I used the one from README. I will try checking if i have right version.

**Comment by chaos5958** [comment]
If you have further problems, please open this issue again.

**Comment by RavaliKolli** [comment]
hi i seem to have new issue when i do the above process, it generates output video for three segments and then has segmentation fault(core dumped).
I have the error log-
#0  0x00007fffe8c6bd1d in torch::CudaIPCSentData::~CudaIPCSentData() ()
   from /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#1  0x00007fffe8c6e5d8 in torch::(anonymous namespace)::CudaIPCGlobalEntities::~CudaIPCGlobalEntities() ()
   from /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#2  0x00007ffff7829ff8 in __run_exit_handlers (status=0, listp=0x7ffff7bb45f8 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#3  0x00007ffff782a045 in __GI_exit (status=<optimized out>) at exit.c:104
#4  0x00007ffff7810837 in __libc_start_main (main=0x5555556377a0 <main>, argc=8, argv=0x7fffffffe368, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe358) at ../csu/libc-start.c:325
#5  0x0000555555717160 in _start () at ../sysdeps/x86_64/elf/start.S:103

I wanted to know if i am still having issue with opencv or any other. Please help me out if you guys can
