### ISSUE TITLE
The link of MPEG_DASH dataset is invalid

### ISSUE THREAD

**Issue by howfars** [kaist-ina/NAS_public#7]
![image](https://user-images.githubusercontent.com/24860642/70312607-eebb7600-184e-11ea-8420-4ec189de82a8.png)

This is the screenshot,so how can I get this dataset?

**Comment by chaos5958** [comment]
Hi, sorry for a invalid link.

I've used my own Dropbox to provide this dataset, 
and I can't maintain this for personal reasons. 

Please try to download your own dataset (e.g., youtube-dl),
and follow the instructions as described in README.

Best, 
Hyunho
