### ISSUE TITLE
Cannot generate MPEG-DASH dataset from the original video

### ISSUE THREAD

**Issue by Hgit007** [kaist-ina/NAS_public#8]
Dear Hyunho Yeo,

The steps I used to install x264 on ubuntu are stated as follows. But I cannot run the command "dash_vid_setup.sh -i [video file]"

**steps:**

- sudo apt-get install yasm

- cd x264

- ./configure --enable-shared --enable-static

- make

- make install

The error information:
![image](https://user-images.githubusercontent.com/39703828/81175827-3109f000-8f72-11ea-985c-886c3966ac8b.png)

Could you please help me to fix the problem? Or could you please share the step how you to install the x264?
Thanks in advance.

Best,

**Comment by chaos5958** [comment]
Hi, I think there is a problem with your a mp4 file.
Could you try with one of Youtube videos (which can be downloaded youtube-dl)?

**Comment by ivancccka** [comment]
hi,I just follow your step of installing x264,but after i type './configure --enable-shared --enable-static',it says No working C compiler found.
could you help me?

**Comment by ivancccka** [comment]
hi i meet the same question with you.could u plez tell how to solve it?
thanks a a lot

**Comment by chaos5958** [comment]
There are pre-built libraries in https://www.videolan.org/developers/x264.html.
Could you try this and open up issue again if it does not work well?

**Comment by ZPWangZP** [comment]
> Dear Hyunho Yeo,
> 
> The steps I used to install x264 on ubuntu are stated as follows. But I cannot run the command "dash_vid_setup.sh -i [video file]"
> 
> **steps:**
> 
> * sudo apt-get install yasm
> * cd x264
> * ./configure --enable-shared --enable-static
> * make
> * make install
> 
> The error information: ![image](https://user-images.githubusercontent.com/39703828/81175827-3109f000-8f72-11ea-985c-886c3966ac8b.png)
> 
> Could you please help me to fix the problem? Or could you please share the step how you to install the x264? Thanks in advance.
> 
> Best,

Have you solved this problem?
