### ISSUE TITLE
can not generates MPEG-DASH from my own video

### ISSUE THREAD

**Issue by ivancccka** [kaist-ina/NAS_public#9]
hi,thank u for your great job.
now i'm running this project on my own computer but i meet some trouble.
i run the code on Windows10.and put my video as the read.md asked.
but after i type"../../dash_vid_setup.sh -i [video_file]",nothing generates.
Here i've downloaded MP4Box and  x264 and i know ther are used to generate MPEG-DASH.but I don't know how use it.
i need your help and thanks a lot.

**Comment by chaos5958** [comment]
Hi ivanccaka, 
I cannot give you a guide based on the given information (also I'm not quite aware of Window environment)..
But, dash_vid_set.sh is just used for setting transcoding a video to support adaptive streaming.
Thus, if your purpose is to test super-resolution performance, you can try our code by preparing a pair of low-resolution and high-resolution videos.
For example, you can easily download Youtube videos using youtube-dl.

**Comment by ivancccka** [comment]
thanks a lot.
and i got 2 questions again.
first,i didn't see steps of using x264 and mp4box,so i guess the two tools are used while typing 'dash_vid_set.sh ',am I right?
second,i've downloaded some videos with different resolutin,and i place it like

data
     ---[dataset name]
             --video_of_240p.mp4
             --video_of_360p.mp4
             --video_of_1080p.mp4

but when i train NAS-MDSR,the error occurs.and i find the 52th line in dataset.py  means the filename should include  'output*k.mp4'.
So is the way i placed  right?or the names of videos  are litmited to some certarin names?
thanks a lot again!

**Comment by ivancccka** [comment]
ok，i've installed x264 and mp4box successfully.but i meet the same quesion with the guy in another open issue while using the youtube video from your link.
while downloading the video,i have a lot of chioces,i think maybe i've downloaded the wrong one,so which one is correct?
![image](https://user-images.githubusercontent.com/48642099/82303008-f6319e80-99ec-11ea-9a7a-3951ed5acb1d.png)

**Comment by chaos5958** [comment]
You should download a video which resolution is 1080p and encoded by h.264.
So, in the above image, 137 would be a right choice.
